#ifndef MAINGRAPHICSITEM_H
#define MAINGRAPHICSITEM_H

enum MainItemData {
    MAIN_SCALE_FACTOR, MAIN_SCALE, SCALE, SCALE2, POSITION_X, POSITION_Y, MAX_INTENSITY_VALUE
};

#endif // MAINGRAPHICSITEM_H
